package mx.lux.pos.java;

/**
 * Created by Benjamin Ivan Martinez Mendoza.
 * User: sucursal
 * Date: 3/06/15
 * Time: 04:09 PM
 * To change this template use File | Settings | File Templates.
 */
public enum TipoParametro {


    ACTIVO_VALIDA_SP( "activo_valida_sp" ),
    ACUSE_LOG_DETALLE( "acuse_log_detalle"),
    ACUSE_RETRASO( "acuse_seg_ciclo" ),
    ANTICIPO_MENOR_REQUIERE_AUTORIZACIN( "anticipo_menor_requiere_autorizacion" ),
    ARCHIVO_MENSAJE( "archivo_mensaje" ),
    ARCHIVO_EMPLEADOS( "archivo_empleados" ),
    ARCHIVO_PRODUCTOS( "archivo_productos" ),
    ARCHIVO_TIPO_CAMBIO( "archivo_tipo_cambio" ),
    ARCHIVO_CLASIFICACION_ARTICULOS( "archivo_clasificacion_articulos" ),
    BANCO_DEPOSITO( "banco_deposito" ),
    CLIENTES_ACTIVOS( "clientes_activos" ),
    COMANDO_IP("comando_ip" ),
    CUPON_TERCER_PAR( "cupon_tercer_par" ),
    FECHA_VALIDA_SEGURO( "fecha_valida_seguro" ),
    PAGOS_NO_TRANSFERENCIA( "pagos_no_transf" ),
    GENERICOS_VALIDOS_OTRAS_TRANS( "genericos_validos_otras_trans" ),
    CAN_MISMO_DIA( "can_mismo_dia" ),
    CONV_NOMINA( "conv_nomina" ),
    COMANDO_ZIP( "comando_zip" ),
    COMPANIA_NOMBRE_CORTO( "compania_nombre_corto" ),
    COMPANIA_REGION( "compania_region" ),
    COMPANIA_RFC( "compania_rfc" ),
    CUPON_FF_ACTIVADO( "cupon_ff" ),
    CUPON_FF_OTHER_DISCOUNT( "cupon_ff_otro_descuento" ),
    DESCRIPCION_CORTA( "descripcion_corta" ),
    DESPLIEGA_USD( "despliega_dolares" ),
    DIA_BODEGA("dia_bodega" ),
    DIA_PRO("DIA_PRO" ),
    EMP_AUDITORIA( "emp_auditoria" ),
    EMP_ELECTRONICO( "emp_electronico" ),
    ESPERA_CIERRE( "espera_cierre" ),
    FECHA_PRIMER_ARRANQUE( "fecha_primer_arranque" ),
    FORMAS_PAGO_NO_CUPON( "formas_pago_no_cupon" ),
    FORMAS_PAGO_DEV( "formas_pago_dev" ),
    FORMATO_ARCHIVO( "formato_archivo_salida" ),
    GRUPO_COMPANIA( "grupo_compania" ),
    GENERICOS_NO_ETREGABLES( "genericos_no_entregables" ),
    GENERICO_PRECIO_VARIABLE( "generico_precio_variable" ),
    GENERICOS_NO_APLICA_DESCUENTO( "genericos_no_aplica_descuento" ),
    ID_CLIENTE_GENERICO( "cli_gen" ),
    ID_ESTADO( "id_estado" ),
    ID_GERENTE( "id_gerente" ),
    ID_SUCURSAL( "id_sucursal" ),
    IMPRESORA_TICKET( "impresora_ticket" ),
    IMPRIME_DUPLICADO( "imprime_duplicado" ),
    INVENTORY_ADJUST_PASSWORD( "clave_ajuste_inventario" ),
    INV_EXCHANGE_FILE_REQUIRED( "inventario_generar_archivo_salida" ),
    INV_EXPORT_ADJUST_TR( "inventario_exportar_tr_ajuste" ),
    INV_EXPORT_ISSUE_TR( "inventario_exportar_tr_salida" ),
    INV_EXPORT_RECEIPT_TR( "inventario_exportar_tr_entrada" ),
    INV_EXPORT_RETURN_TR( "inventario_exportar_tr_devolucion" ),
    INV_EXPORT_SALE_TR( "inventario_exportar_tr_venta" ),
    IVA_VIGENTE( "iva_vigente" ),
    MAX_DISCOUNT_STORE( "tope_descto_tienda" ),
    MAX_LONG_DESC_FACTURA( "max_long_desc_efactura" ),
    METODO_BUSQUEDA_ARTICULOS( "metodo_busqueda_articulos" ),
    MOSTRAR_NO_STOCK_TICKET_LC( "mostrar_no_stock_ticket_lc" ),
    MONTO_GENERA_FF_CUPON( "monto_genera_ff_cupon" ),
    MONTO_APLICA_FF_CUPON( "monto_aplica_ff_cupon" ),
    MONTO_FF_CUPON( "monto_ff_cupon" ),
    PAQUETES("paquetes" ),
    PEDIDO_LC( "pedido_lc" ),
    PIDE_FACTURA( "pide_factura" ),
    PORCENTAJE_ANTICIPO( "porcentaje_anticipo" ),
    PORCENTAJE_GARANTIA( "porcentaje_garantia" ),
    RUTA_CIERRE( "ruta_cierre" ),
    RUTA_COMPROBANTES( "ruta_comprobantes" ),
    COMANDO_BKP_NOTA( "comando_bkp_venta" ),
    RUTA_INVENTARIO( "ruta_inv_tr" ),
    RUTA_REMISION( "ruta_remision" ),
    RUTA_LISTA_PRECIOS( "ruta_lista_precios" ),
    RUTA_POR_ENVIAR( "ruta_por_enviar" ),
    RUTA_POR_ENVIAR_DROPBOX( "ruta_por_enviar_dropbox" ),
    RUTA_POR_ENVIAR_MENSAJERO( "ruta_por_enviar_mensajero" ),
    RUTA_POR_RECIBIR( "ruta_por_recibir" ),
    RUTA_RECIBIDOS( "ruta_recibidos" ),
    RUTA_CATALOGOS( "ruta_catalogos" ),
    SALIDA_TOTAL_ACTIVA( "salida_total_activa" ),
    TIPO_PAGO( "tipo_pago" ),
    TIPO_PAGO_DOLARES( "tipo_pago_dolares" ),
    TIPO_PAGO_CRE_EMP( "tipo_pago_credito_emp" ),
    TRANS_CAN_MISMO_DIA( "trans_can_mismo_dia" ),
    TRANS_INV_TIPO_AJUSTE( "trans_inv_tipo_ajuste" ),
    TRANS_INV_TIPO_CANCELACION( "trans_inv_tipo_cancelacion" ),
    TRANS_INV_TIPO_CANCELACION_EXTRA( "trans_inv_tipo_canc_extraordinaria" ),
    TRANS_INV_TIPO_RECIBE_REMISION( "trans_inv_tipo_recibe_remision" ),
    TRANS_INV_TIPO_SALIDA( "trans_inv_tipo_salida" ),
    TRANS_INV_TIPO_OTRA_SALIDA( "trans_inv_tipo_otra_salida" ),
    TRANS_INV_TIPO_OTRA_ENTRADA( "trans_inv_tipo_otra_entrada" ),
    TRANS_INV_TIPO_VENTA( "trans_inv_tipo_venta" ),
    TRANS_INV_TIPO_ENTRADA_SP( "trans_inv_tipo_recibe_remision_sp" ),
    URL_ACUSE_AJUSTE_VENTA( "url_acuse_ajuste_venta" ),
    URL_ACUSE_VENTA_DIA( "url_acuse_venta_dia" ),
    URL_CARGA_LISTA_PRECIOS( "url_carga_lista_precios"),
    URL_RECIBE_LISTA_PRECIOS( "url_recibe_lista_precios" ),
    VALIDA_SP( "valida_sp" ),
    SALIDA_VENTA_SP( "salida_venta_sp" ),
    VALIDA_EMPLEADO( "valida_empleado" ),
    VALIDA_DIA_CERRADO_VENTA( "valida_dia_cerrado_venta" ),
    VALIDA_APLICAR_CUPON_PUBLICO_GENERAL( "valida_aplicar_cupon_publico_general" ),
    VENTA_NEGATIVA_AUTORIZACION( "venta_negativo_aut" ),
    VIGENCIA_CUPON("vigencia_cupon" ),
    VIGENCIA_CUPON_FF("vigencia_cupon_ff" ),
    VIGENCIA_SEGURO_INFANTIL("vigencia_seguro_infantil" ),
    VIGENCIA_SEGURO_OFTALMICO("vigencia_seguro_oftalmico" ),
    VIGENCIA_SEGURO_SOLAR("vigencia_seguro_solar" ),
    ALMACENES("almacenes" ),
    ALMACEN_POR_ACLARAR("almacen_por_aclarar" ),
    ACTIVE_STORE_DISCOUNT( "desc_tienda_activo" ),
    ARCHIVO_CONSULTA_WEB("archivo_consulta_web" ),
    URL_ACUSE_RECIBIDO_LC("url_acuse_recibido_lc" ),
    URL_CANCELACION_PEDIDO_LC("cancelacion_pedido_lc" ),
    URL_REUSO_PEDIDO_LC("reuso_pedido_lc" ),
    URL_SALIDA_ALMACEN("url_salida_almacen" ),
    URL_ENTRADA_ALMACEN("url_entrada_sucursal" ),
    URL_CONFIRMA_ENTRADA("url_confirma_entrada" ),
    USUARIO_SISTEMAS("usuario_sistemas" ),
    TRANS_INV_TIPO_SALIDA_ALMACEN( "trans_inv_salida_almacen"  ),
    TRANS_INV_TIPO_ENTRADA_ALMACEN( "trans_inv_entrada_almacen" ),
    TERMINAL_CAJA("terminal_caja" ),
    INV_EXPORT_SALIDA_ALMACEN_TR( "inventario_exportar_tr_salida_almacen" ),
    INV_EXPORT_ENTRADA_ALMACEN_TR( "inventario_exportar_tr_entrada_almacen" );


    private final String valor;

    TipoParametro (String valor) {
      this.valor = valor;
    }


    public String getValor() {
      return valor;
    }
}
